#!/bin/bash
# utilities to ease various aws manipulation operations on an EC2 instance
# They can be called via $(aws-utils subcommand args) or you can call $(aws-utils install-commands)
# and from then on, any of them can be called without the aws-utils prefix.
# export the a non-empty variable VERBOSE to get diagnostic logging

# Internal functions
die() {
  local message="$1"
  local exit_code="${2:-1}"  # Default exit code is 1 if not provided.
  echo "Error!:  $message" >&2  # Print message to stderr.
  exit "$exit_code"  # Exit with the provided exit code.
}

say() {
  if [ -n "$VERBOSE" ]; then
    echo "$1" >&2
  fi
}

usage() {
  local joined_subcommands="${SUBCOMMANDS[@]// /|}"

  die "usage: $1 <${joined_subcommands}|install-commands> args"
}

IMDS_HOST_URI="http://169.254.169.254"

# Function to retrieve a new token from IMDSv2
get_imds_token() {
  # Determine a user-writable token file path
  USER_ID=$(id -u)
  local runtime_data_directory="/run/user/${USER_ID}"
  local imds_token_file="${runtime_data_directory}/imds_token"
  # Ensure the token file directory exists
  mkdir -p "${runtime_data_directory}" && chmod 700 "${runtime_data_directory}" || die "cannot create runtime data directory ${runtime_data_directory}"

  local ttl_seconds=21600  # 6 hours
  local stale_seconds=$((ttl_seconds - 60))

  if [[ ! -f "$imds_token_file" ]] || [[ $(($(date +%s) - $(stat -c %Y "$imds_token_file"))) -gt $stale_seconds ]]; then
    say "Fetching a new IMDSv2 token..."
    IMDS_TOKEN=$(curl -s -X PUT "$IMDS_HOST_URI/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: $ttl_seconds")

    if [[ -z "$IMDS_TOKEN" ]]; then
      die  "Error: Failed to retrieve IMDSv2 token."
    fi

    echo "$IMDS_TOKEN" > "$imds_token_file"
    chmod 600 "$imds_token_file"
  else
    IMDS_TOKEN=$(cat "$imds_token_file")
  fi
}

matches_ip_address() {
  if [[ $1 =~ ^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$ ]]; then
    return 0
  else
    return 1
  fi
}

resolve_hostname() {
  [ $# -ne 1 ] && die "Usage: $0 <hostname>"
  local host_output
  host_output=$(host $1)
  [ $? -ne 0 ] && return 1
  local ip_address
  ip_address=$(echo "$host_output" | awk '/has address/ { print $NF }' | head -1)
  if  matches_ip_address $ip_address; then
    echo $ip_address
  else
    return 1
  fi
}

eva_usage() {
  die "usage:  $1 <ebs-volume-id> <mount-point>
                ebs-volume-id must match vol-*
                mount point must be under /mnt"
}

get_my_instance_id() {
  # Fetch the instance ID and region from instance metadata
  MY_INSTANCE_ID=$(IMDSCurl latest/meta-data/instance-id)
  if ! [[ $MY_INSTANCE_ID =~ ^i-[0-9a-f]+$ ]]; then
    die "Error: Failed to retrieve instance ID."
  fi
}

get_my_region() {
  MY_AWS_REGION=$(IMDSCurl latest/dynamic/instance-identity/document | jq -r .region)

  if ! [[ $MY_AWS_REGION =~ ^[a-z]{2}-[a-z]+-[1-9]$ ]]; then
    die "Error: Failed to retrieve my aws region."
  fi
}

next_available_disk_device() {
  [ -n "$MY_INSTANCE_ID" ] || get_my_instance_id
  [ -n "$MY_AWS_REGION" ] || get_my_region

  # Check currently attached devices
  local attached_volumes=$(aws ec2 describe-instances --instance-ids "$MY_INSTANCE_ID" \
    --region "$MY_AWS_REGION" --query 'Reservations[].Instances[].BlockDeviceMappings[].DeviceName' \
    --output text)

  # Define a list of potential device names
  local possible_device_names="/dev/sdf /dev/sdg /dev/sdh /dev/sdi /dev/sdj /dev/sdk /dev/sdl"

  # Find the first available device_name
  local device_name
  for device_name in $possible_device_names; do
    # check if the device_name is an existing partition or a symlink pointing to an existing
    # disk partition
    if grep -Fq "$(basename "$device_name")" /proc/partitions ||  \
          ([ -L "$device_name" ] && grep -Fq "$(readlink "$device_name")" /proc/partitions)
    then
      say "$device_name is attached to a partition"
    else
      if ! echo "$attached_volumes" | grep -Fq "$device_name"; then
        echo -n "$device_name"
        return 0
      fi
    fi
  done

  die "No available disk device found."
}

# the following functions are exposed as subcommands
#
SUBCOMMANDS=("IMDSCurl associate_this_elastic_ip_address_with_me ensure_volume_attached")


IMDSCurl() {

  if [[ -z "$1" ]]; then
    die "Usage: $0 <metadata-path|full-url>"
  fi

  get_imds_token

  local url_path="$1"

  # Allow full URL or path specification only if it matches IMDS_HOST_URI
  # (prevent using this command to exfiltrate the IMDS_TOKEN to other web servers)
  if [[ "$url_path" == ${IMDS_HOST_URI}/* ]]; then
    URL="$url_path"
  else
    URL="$IMDS_HOST_URI/$url_path"
  fi

  # Fetch the metadata
  curl -s -H "X-aws-ec2-metadata-token: $IMDS_TOKEN" "$URL" || die "cannot fetch metadata $1"
}


ensure_volume_attached() {
  local ebs_vol_id="$1"
  local local_mount_point="$2"

  # confirm that each matches the proper regex
  if [[ "$ebs_vol_id" =~ ^vol-[0-9a-f]{8,17}$ ]] && [[ "$local_mount_point" =~ ^/.+$ ]]
  then
    mkdir -p "$local_mount_point"
    [ -d "$local_mount_point" ] || die "Could not mkdir $local_mount_point"
  else
    eva_usage $0
  fi

  get_my_instance_id
  get_my_region

  local attached_volumes_data="$(aws ec2 describe-volumes --region "$MY_AWS_REGION" \
            --filters "Name=attachment.instance-id,Values=$MY_INSTANCE_ID" --output json)"
  [ "$?" = "0" ] || die "could not describe-volumes"

  local attached_device=$(echo "$attached_volumes_data" | \
                              jq -r --arg ebs_vol_id "$ebs_vol_id" \
                            --arg THE_INSTANCE_ID "$MY_INSTANCE_ID" '
            .Volumes[]
            | select(.VolumeId == $ebs_vol_id and .Attachments[].InstanceId == $THE_INSTANCE_ID)
            | .Attachments[].Device
        ')

  local attach_point="$(next_available_disk_device)"

  if [ -n "$attached_device" ]; then
    echo -n "$attached_device"
    return 0
  fi

  [ -n "$attach_point" ] || die "no available attach point found"
  aws ec2 attach-volume --volume-id "$ebs_vol_id" --instance-id "$MY_INSTANCE_ID" \
        --device "$attach_point" || die "Could not attach the volume $ebs_vol_id to my instance id"

  # TODO:  find the device id of the filesystem paritition and mount it on $local_mount_point
  die "mount unimplemented as of yet"
}

associate_this_elastic_ip_address_with_me() {
  if [ "$#" -ne 1  ] || [[ "$1" =~ ^- ]] ; then
    die "Usage: $0 <host_or_ip_address>"
  fi

  local host_or_ip_address="${1}"

  if matches_ip_address $host_or_ip_address; then
    THE_ELASTIC_IP=$host_or_ip_address
  else
    THE_ELASTIC_IP=$(resolve_hostname $host_or_ip_address )
    [ $? -ne 0 ] && die "Cannot resolve hostname $host_or_ip_address"
  fi


  get_my_instance_id
  get_my_region


  # Attach the Elastic IP to myself
  aws ec2 associate-address --instance-id $MY_INSTANCE_ID --public-ip $THE_ELASTIC_IP \
                            --region $MY_AWS_REGION
}


INVOKED_AS=$(basename "$0")

# first check if running in installed command mode
for subcommand in $SUBCOMMANDS
do
  if [ "$INVOKED_AS" = "$subcommand" ]; then
    $subcommand "$@"
    exit $?
  fi
done


# next, check if running with a valid subcommand
for subcommand in $SUBCOMMANDS
do
  if [ "$1" = "$subcommand" ] ; then
    shift
    $subcommand $@
    exit $?
  fi
done

if [ $1 = 'install-commands' ] ; then
  THIS_SCRIPT_PATH="${BASH_SOURCE[0]}"
  THIS_SCRIPT_NAME="$(basename "$THIS_SCRIPT_PATH")"
  THIS_SCRIPT_DIR="$( cd "$( dirname "$THIS_SCRIPT_PATH" )" &> /dev/null && pwd )"
  INSTALL_DIR="$THIS_SCRIPT_DIR"
  for subcommand in $SUBCOMMANDS
  do
    SYMLINK="$THIS_SCRIPT_DIR/$subcommand"
    TARGET="$THIS_SCRIPT_NAME"
    ln -s "$TARGET" "$SYMLINK" || die "could not symlink $SYMLINK to $TARGET"
  done
  exit 0
fi

usage $0

